[32m2025-06-04 16:31:57 -0600[0m - dagster - [34mDEBUG[0m - bronze_job - feb6f4f6-79fb-4a71-bb1f-52f75b94099a - 1882950 - LOGS_CAPTURED - Started capturing logs in process (pid: 1882950).
[32m2025-06-04 16:31:57 -0600[0m - dagster - [34mDEBUG[0m - bronze_job - feb6f4f6-79fb-4a71-bb1f-52f75b94099a - 1882950 - cancellations_bronze - STEP_START - Started execution of step "cancellations_bronze".
25/06/04 16:32:00 WARN Utils: Your hostname, engineer resolves to a loopback address: 127.0.1.1; using 192.168.0.216 instead (on interface wlp1s0)
25/06/04 16:32:00 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
25/06/04 16:32:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/06/04 16:32:04 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
25/06/04 16:32:04 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
25/06/04 16:32:04 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[32m2025-06-04 16:32:17 -0600[0m - dagster - [34mERROR[0m - [31mbronze_job - feb6f4f6-79fb-4a71-bb1f-52f75b94099a - 1882950 - cancellations_bronze - STEP_FAILURE - Execution of step "cancellations_bronze" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "cancellations_bronze"::

pyspark.errors.exceptions.captured.AnalysisException: [DELTA_PARTITION_COLUMN_NOT_FOUND] Partition column `plan` not found in schema [cancel_id, member_id, days_offset, timestamp, reason]

Stack Trace:
  File "/home/jake/dev/body_by_jake/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/home/jake/dev/body_by_jake/.venv/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
  File "/home/jake/dev/body_by_jake/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/home/jake/dev/body_by_jake/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/home/jake/dev/body_by_jake/bbj_dagster/assets/bronze_assets.py", line 46, in cancellations_bronze
    write_partitioned_delta(df, f"{BRONZE_PATH}/cancellations")
  File "/home/jake/dev/body_by_jake/bbj_dagster/assets/bronze_assets.py", line 16, in write_partitioned_delta
    .save(path)
  File "/home/jake/dev/body_by_jake/.venv/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 1463, in save
    self._jwrite.save(path)
  File "/home/jake/dev/body_by_jake/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/jake/dev/body_by_jake/.venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
[0m
